export enum ClinicalInteractionType {
  AFFECTED_BY_SALTS = 'AFFECTED_BY_SALTS',
  AFFECTED_BY_CALCIUM = 'AFFECTED_BY_CALCIUM',
  AFFECTED_BY_SUCRALFATE = 'AFFECTED_BY_SUCRALFATE',
  OPHTHALMIC_MIN_INTERVAL = 'OPHTHALMIC_MIN_INTERVAL',
}
